name: pydata-pdx-pytorchlightning
channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.7.11
  - pytorch
  - jupyterlab
  - pandas
  - ipywidgets
  - jupyter-server-proxy
  - pip
  - pip:
    - pytorch-lightning==1.4.9
    - tensorflow